version: '3'
services:
  core:
    build: server
    ports:
     - "3000:3000"
    links:
     - redis
    depends_on:
     - redis
    environment:
     - NODE_ENV=production
     - HTTPS=true
    volumes:
     - "./local-certs:/keys"
  redis:
    build: redis/.
    ports:
     - "6379:6379"
    volumes:
     - "./redis/data:/var/lib/redis"
  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile.prod
      args:
       - CORE_HOSTNAME=localhost
       - CORE_PORT=3000
       - CORE_PROTOCOL=https
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "./webapp/nginx.local-prod.conf:/etc/nginx/nginx.conf"
     - "./local-certs:/keys"
