version: '3'
services:
  server:
    build: server/.
    ports:
     - "3000:3000"
    links:
     - redis
    depends_on:
     - redis
    environment:
     - NODE_ENV=development
  redis:
    image: "redis:alpine"
